@extends('layouts.admin')
@section('title','Dashboard')
@section('page_title','Humelix Operations Dashboard')
@section('page_subtitle','Monitor enquiries, projects, services, videos, equipment, branches and content activity.')
@section('page_actions')
<div class="admin-heading-actions">
    <form class="admin-date-filter" method="GET"><x-admin-icon name="calendar"/><select name="period" aria-label="Dashboard date range" onchange="this.form.submit()"><option value="7" @selected($period===7)>Last 7 days</option><option value="14" @selected($period===14)>Last 14 days</option><option value="30" @selected($period===30)>Last 30 days</option></select></form>
    <a class="btn btn-outline" href="{{ route('home') }}" target="_blank" rel="noopener"><x-admin-icon name="external"/> View Website</a>
    @if(auth()->user()?->canManage('articles'))<a class="btn btn-primary" href="{{ route('admin.articles.create') }}"><x-admin-icon name="articles"/> New Article</a>@endif
    @if(auth()->user()?->canManage('projects'))<a class="btn btn-primary" href="{{ route('admin.projects.create') }}"><x-admin-icon name="projects"/> Add Project</a>@endif
    @if(auth()->user()?->canManage('videos'))<a class="btn btn-primary" href="{{ route('admin.videos.create') }}"><x-admin-icon name="videos"/> Add Video</a>@endif
    @if(auth()->user()?->canManage('enquiries'))<a class="btn btn-outline" href="{{ route('admin.enquiries.index') }}"><x-admin-icon name="enquiries"/> View Enquiries</a>@endif
</div>
@endsection
@section('content')
@php
    $kpis = [
        ['totalEnquiries','Total Enquiries','enquiries','All time enquiries','blue'],
        ['newEnquiries','New Enquiries','enquiries','Needs attention','cyan'],
        ['projects','Projects','projects','Case studies','indigo'],
        ['branches','Branches','branches','Operating locations','green'],
        ['jobs','Jobs / Careers','careers','Openings and archives','purple'],
        ['equipmentItems','Equipment Items','equipment','Vendor catalogue','amber'],
        ['videos','Videos','videos','Library assets','cyan'],
        ['reviews','Reviews','reviews','Social proof','amber'],
        ['articles','Articles / Resources','articles','Content library','purple'],
        ['teamMembers','Team Members','team','People profiles','green'],
    ];
@endphp
<section class="admin-kpi-grid" aria-label="Key performance indicators">
@foreach($kpis as [$key,$label,$icon,$helper,$tone])
    <article class="admin-kpi admin-reveal"><div class="admin-kpi-top"><span class="admin-kpi-icon is-{{ $tone }}"><x-admin-icon :name="$icon"/></span><span class="admin-kpi-trend"><x-admin-icon name="trend"/> Live</span></div><p>{{ $label }}</p><strong>{{ number_format($stats[$key] ?? 0) }}</strong><small>{{ $helper }}</small></article>
@endforeach
</section>

<section class="admin-analytics-grid">
    <article class="admin-panel admin-chart-panel admin-reveal"><header class="admin-panel-head"><div><h2>Enquiries over last {{ $period }} days</h2><p>Daily request volume from public forms and chat.</p></div><span class="admin-panel-chip">Daily</span></header><div class="admin-chart-wrap">@if(collect($chartData['enquiryTrend']['values'])->sum() > 0)<canvas data-enquiry-trend aria-label="Enquiries over the selected period"></canvas>@else@include('admin.partials.empty',['title'=>'No enquiry activity yet','message'=>'New enquiries will appear in this trend.'])@endif</div></article>
    <article class="admin-panel admin-chart-panel admin-reveal"><header class="admin-panel-head"><div><h2>Enquiries by Type of Work</h2><p>HVAC, Solar, Electrical, Maintenance, Vendor and other request patterns.</p></div></header><div class="admin-chart-wrap admin-chart-doughnut">@if(collect($chartData['enquiryTypes']['values'])->sum() > 0)<canvas data-enquiry-type-chart aria-label="Enquiry type breakdown"></canvas>@else@include('admin.partials.empty',['title'=>'No type data yet','message'=>'Enquiry type data will appear here.'])@endif</div></article>
    <article class="admin-panel admin-chart-panel admin-reveal"><header class="admin-panel-head"><div><h2>Project / Service Distribution</h2><p>Published and draft project mix by service division.</p></div></header><div class="admin-chart-wrap">@if(collect($chartData['projects']['values'])->sum() > 0)<canvas data-project-chart aria-label="Project service distribution"></canvas>@else@include('admin.partials.empty',['title'=>'No project distribution yet','message'=>'Project service mix will appear here.'])@endif</div></article>
    <article class="admin-panel admin-chart-panel admin-reveal"><header class="admin-panel-head"><div><h2>Videos & Equipment</h2><p>Content catalogue mix by category.</p></div></header><div class="admin-chart-wrap">@if(collect($chartData['catalogue']['values'])->sum() > 0)<canvas data-video-equipment-chart aria-label="Video and equipment category distribution"></canvas>@else@include('admin.partials.empty',['title'=>'No catalogue data yet','message'=>'Video and equipment category data will appear here.'])@endif</div></article>
</section>

<section class="admin-data-grid">
    <article class="admin-panel admin-reveal"><header class="admin-panel-head"><div><h2>Recent Enquiries</h2><p>Latest leads requiring attention.</p></div><a href="{{ route('admin.enquiries.index') }}" class="admin-text-link">View all →</a></header><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Client</th><th>Work</th><th>Location</th><th>Status</th><th>Date</th><th></th></tr></thead><tbody>@forelse($recentEnquiries as $enquiry)<tr><td><strong>{{ $enquiry->name }}</strong><small>{{ $enquiry->phone }}</small></td><td>{{ $enquiry->display_type_of_work }}</td><td>{{ $enquiry->display_location ?: '—' }}</td><td><span class="status-badge status-{{ $enquiry->status }}">{{ ucwords(str_replace('_',' ',$enquiry->status)) }}</span></td><td>{{ $enquiry->created_at->format('M j') }}</td><td><a class="admin-row-action" href="{{ route('admin.enquiries.show',$enquiry) }}">View</a></td></tr>@empty<tr><td colspan="6">@include('admin.partials.empty',['title'=>'No enquiries yet','message'=>'New customer enquiries will appear here.'])</td></tr>@endforelse</tbody></table></div></article>
    <article class="admin-panel admin-reveal"><header class="admin-panel-head"><div><h2>Recent Projects</h2><p>Recently updated case studies.</p></div><a href="{{ route('admin.projects.index') }}" class="admin-text-link">Manage →</a></header><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Project</th><th>Location</th><th>Status</th><th></th></tr></thead><tbody>@forelse($recentProjects as $project)<tr><td><strong>{{ $project->title }}</strong><small>{{ $project->service_division ?: $project->system_type }}</small></td><td>{{ $project->location }}</td><td><span class="status-badge status-{{ $project->status }}">{{ ucfirst($project->status) }}</span></td><td><a class="admin-row-action" href="{{ route('admin.projects.edit',$project) }}">Edit</a></td></tr>@empty<tr><td colspan="4">@include('admin.partials.empty',['title'=>'No projects yet','message'=>'Create a project to start your case-study library.'])</td></tr>@endforelse</tbody></table></div></article>
</section>

<section class="admin-data-grid">
    <article class="admin-panel admin-reveal"><header class="admin-panel-head"><div><h2>Recent Videos</h2><p>Latest video library records.</p></div><a href="{{ route('admin.videos.index') }}" class="admin-text-link">Manage →</a></header><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Video</th><th>Category</th><th>Status</th><th></th></tr></thead><tbody>@forelse($recentVideos as $video)<tr><td><strong>{{ $video->title }}</strong><small>{{ $video->video_type }}</small></td><td>{{ $video->category ?: '—' }}</td><td><span class="status-badge status-{{ $video->status }}">{{ $video->status }}</span></td><td><a class="admin-row-action" href="{{ route('admin.videos.edit',$video) }}">Edit</a></td></tr>@empty<tr><td colspan="4">@include('admin.partials.empty',['title'=>'No videos yet','message'=>'Add external or uploaded videos for project and service pages.'])</td></tr>@endforelse</tbody></table></div></article>
    <article class="admin-panel admin-reveal"><header class="admin-panel-head"><div><h2>Recent Equipment</h2><p>Latest Vendor catalogue entries.</p></div><a href="{{ route('admin.equipment.index') }}" class="admin-text-link">Manage →</a></header><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Item</th><th>Category</th><th>Published</th><th></th></tr></thead><tbody>@forelse($recentEquipment as $item)<tr><td><strong>{{ $item->name }}</strong><small>{{ str_replace('_',' ', $item->availability_status) }}</small></td><td>{{ $item->category }}</td><td>{{ $item->is_published ? 'Yes' : 'No' }}</td><td><a class="admin-row-action" href="{{ route('admin.equipment.edit',$item) }}">Edit</a></td></tr>@empty<tr><td colspan="4">@include('admin.partials.empty',['title'=>'No equipment yet','message'=>'Add request-based Vendor equipment items.'])</td></tr>@endforelse</tbody></table></div></article>
</section>

<section class="admin-bottom-grid">
    <article class="admin-panel admin-reveal"><header class="admin-panel-head"><div><h2>Open Jobs</h2><p>Career opportunities currently being managed.</p></div><a class="admin-text-link" href="{{ route('admin.jobs.index') }}">Manage →</a></header><div class="admin-table-wrap"><table class="admin-table"><tbody>@forelse($openJobs as $job)<tr><td><strong>{{ $job->title }}</strong><small>{{ $job->location ?: 'Global' }} · {{ $job->employment_type ?: 'Role' }}</small></td><td><span class="status-badge status-{{ $job->status }}">{{ $job->status }}</span></td><td><a class="admin-row-action" href="{{ route('admin.jobs.edit',$job) }}">Edit</a></td></tr>@empty<tr><td>@include('admin.partials.empty',['title'=>'No open jobs','message'=>'Open job postings will appear here.'])</td></tr>@endforelse</tbody></table></div></article>
    <article class="admin-panel admin-reveal"><header class="admin-panel-head"><div><h2>Pending Reviews</h2><p>Client feedback awaiting moderation.</p></div><a class="admin-text-link" href="{{ route('admin.reviews.index') }}">View all →</a></header><div class="review-overview"><div class="review-score"><strong>{{ number_format($reviewSummary['average'],1) }}</strong><span class="stars">★★★★★</span><small>{{ $reviewSummary['approved'] }} approved · {{ $reviewSummary['pending'] }} pending</small></div><div class="review-snippets">@forelse($pendingReviews as $review)<blockquote><div><strong>{{ $review->client_name }}</strong><span>{{ str_repeat('★',$review->rating) }}</span></div><p>“{{ \Illuminate\Support\Str::limit($review->comment,90) }}”</p></blockquote>@empty<p class="meta">No pending reviews.</p>@endforelse</div></div></article>
    <article class="admin-panel admin-reveal"><header class="admin-panel-head"><div><h2>Operational Alerts</h2><p>Small checklist for daily admin review.</p></div></header><ul class="admin-alert-list">@foreach($operationalAlerts as $alert)@if(auth()->user()?->canManage($alert['module']))<li><a href="{{ route($alert['route']) }}"><span class="status-dot is-{{ $alert['tone'] }}"></span><strong>{{ number_format($alert['count']) }}</strong><span>{{ $alert['label'] }}</span></a></li>@endif @endforeach</ul></article>
</section>

<section class="admin-bottom-grid">
    <article class="admin-panel admin-reveal"><header class="admin-panel-head"><div><h2>Quick Actions</h2><p>Common administrative tasks.</p></div></header><div class="quick-action-grid">@if(auth()->user()?->canManage('projects'))<a href="{{ route('admin.projects.create') }}"><x-admin-icon name="projects"/>Add Project</a>@endif @if(auth()->user()?->canManage('branches'))<a href="{{ route('admin.branches.create') }}"><x-admin-icon name="branches"/>Add Branch</a>@endif @if(auth()->user()?->canManage('jobs'))<a href="{{ route('admin.jobs.create') }}"><x-admin-icon name="careers"/>Add Job</a>@endif @if(auth()->user()?->canManage('equipment'))<a href="{{ route('admin.equipment.create') }}"><x-admin-icon name="equipment"/>Add Equipment Item</a>@endif @if(auth()->user()?->canManage('videos'))<a href="{{ route('admin.videos.create') }}"><x-admin-icon name="videos"/>Add Video</a>@endif @if(auth()->user()?->canManage('articles'))<a href="{{ route('admin.articles.create') }}"><x-admin-icon name="articles"/>Create Article</a>@endif @if(auth()->user()?->canManage('reviews'))<a href="{{ route('admin.reviews.index') }}"><x-admin-icon name="reviews"/>Manage Reviews</a>@endif @if(auth()->user()?->canManage('settings'))<a href="{{ route('admin.settings.edit') }}"><x-admin-icon name="settings"/>Update Site Settings</a>@endif</div></article>
    <article class="admin-panel admin-reveal"><header class="admin-panel-head"><div><h2>Review Status</h2><p>Approved versus pending social proof.</p></div></header><div class="admin-chart-wrap admin-chart-doughnut">@if(collect($chartData['reviews']['values'])->sum() > 0)<canvas data-review-chart aria-label="Review status summary"></canvas>@else@include('admin.partials.empty',['title'=>'No reviews yet','message'=>'Review status will appear here.'])@endif</div></article>
    <article class="admin-panel admin-reveal"><header class="admin-panel-head"><div><h2>System Status</h2><p>Operational readiness.</p></div></header><dl class="system-list"><div><dt>Application</dt><dd><i class="status-dot is-good"></i> Online</dd></div><div><dt>Storage link</dt><dd><i class="status-dot {{ $systemStatus['storageLinked'] ? 'is-good' : 'is-warn' }}"></i> {{ $systemStatus['storageLinked'] ? 'Ready' : 'Check' }}</dd></div><div><dt>Environment</dt><dd>{{ ucfirst($systemStatus['environment']) }}</dd></div><div><dt>Debug mode</dt><dd>{{ $systemStatus['debug'] ? 'Enabled' : 'Disabled' }}</dd></div><div><dt>Last checked</dt><dd>{{ $systemStatus['updatedAt']->format('H:i') }}</dd></div></dl></article>
</section>
@endsection
@push('head')
@vite('resources/js/admin-dashboard.js')
<script>window.HUMELIX_ADMIN_CHARTS = @json($chartData);</script>
@endpush
